Repository kmc-jp/puzzleGame2023, pull requests merged in 2023-08, with the labels that each got.

#41 12 attach colider
  Assets/Scripts/GMforTest01.cs
Labels: priority: high, status: fix needed, type: discussion

#40 5 goal object
  Assets/Scenes/TestScene01.unity
  Assets/Scripts/GMforTest01.cs
  Assets/Scripts/GameLogicData.cs
  Assets/Scripts/GameLogicData.cs.meta
  Assets/Scripts/GameLogicMnager.cs
  Assets/Scripts/GameLogicMnager.cs.meta
  Assets/Scripts/LineObjectM.cs
  Assets/Scripts/LineObjectM.cs.meta
  Assets/Scripts/PlayerManager.cs
  Assets/Scripts/PlayerManager.cs.meta
  Assets/Scripts/StageManager.cs
  Assets/Scripts/StageManager.cs.meta
  Assets/Scripts/UIinkM.cs
Labels: priority: high, status: in progress, status: fix needed

#44 (#30) 部屋設定画面のUI設計
  Assets/Prefabs/RoomSetting/MemberBanner.prefab
  Assets/Prefabs/RoomSetting/MemberBanner.prefab.meta
  Assets/Prefabs/RoomSetting/MemberBannerList.prefab
  Assets/Prefabs/RoomSetting/MemberBannerList.prefab.meta
  Assets/Prefabs/RoomSetting/PlayerBanner.prefab
  Assets/Prefabs/RoomSetting/PlayerBanner.prefab.meta
  Assets/Scenes/RoomSelectScene.unity
  Assets/Scenes/RoomSelectScene.unity.meta
  Assets/Scenes/RoomSetting.unity
  Assets/Scenes/RoomSetting.unity.meta
Labels: status: approved
