Repository kmc-jp/puzzleGame2023, pull requests merged in 2023-09, with the labels that each got.

#67 54 blue anima
  Assets/Physics/BlueAnimaMaterial.physicsMaterial2D
  Assets/Physics/BlueAnimaMaterial.physicsMaterial2D.meta
  Assets/Scenes/TestScene01.unity
  Assets/Scripts/BlueAnimaMovementBehaviour.cs
  Assets/Scripts/BlueAnimaMovementBehaviour.cs.meta
  Assets/Scripts/GMforTest01.cs
  Assets/Scripts/GMforTest01.cs.meta
  Assets/Scripts/LineObjectM.cs
  Assets/Scripts/StageManager.cs
Labels: status: approved

#70 66 anima implementation improvements
  Assets/Anima.meta
  Assets/Anima/BlueAnimaTemplate.prefab
  Assets/Anima/BlueAnimaTemplate.prefab.meta
  Assets/Anima/GreenAnimaTemplate.prefab
  Assets/Anima/GreenAnimaTemplate.prefab.meta
  Assets/Anima/PurpleAnimaTemplate.prefab
  Assets/Anima/PurpleAnimaTemplate.prefab.meta
  Assets/Anima/RedAnimaTemplate.prefab
  Assets/Anima/RedAnimaTemplate.prefab.meta
  Assets/Anima/YellowAnimaTemplate.prefab
  Assets/Anima/YellowAnimaTemplate.prefab.meta
  Assets/Scenes/TestScene01.unity
  Assets/Scripts/AnimaCanvas.cs
  Assets/Scripts/AnimaCanvas.cs.meta
  Assets/Scripts/AnimaObject.cs
  Assets/Scripts/AnimaObject.cs.meta
  Assets/Scripts/BlueAnimaMovementBehaviour.cs
  Assets/Scripts/CursorInteractable.cs
  Assets/Scripts/GMforTest01.cs
  Assets/Scripts/GMforTest01.cs.meta
  Assets/Scripts/GreenAnimaMovementBehaviour.cs
  Assets/Scripts/GreenAnimaMovementBehaviour.cs.meta
  Assets/Scripts/InteractableCursorController.cs
  Assets/Scripts/LineObjectM.cs
  Assets/Scripts/PlayerManager.cs
  Assets/Scripts/PurpleAnimaMovementBehaviour.cs
  Assets/Scripts/PurpleAnimaMovementBehaviour.cs.meta
  Assets/Scripts/RedAnimaMovementBehaviour.cs
  Assets/Scripts/RedAnimaMovementBehaviour.cs.meta
  Assets/Scripts/StageInputController.cs
  Assets/Scripts/StageInputController.cs.meta
  Assets/Scripts/UIinkM.cs
  Assets/Scripts/YellowAnimaMovementBehaviour.cs
  Assets/Scripts/YellowAnimaMovementBehaviour.cs.meta
  ProjectSettings/InputManager.asset
  ProjectSettings/TagManager.asset
Labels: priority: high, status: review needed

#77 76 import dotween library
  Assets/Plugins/Demigiant.meta
  Assets/Plugins/Demigiant/DOTween.meta
  Assets/Plugins/Demigiant/DOTween/DOTween.XML
  Assets/Plugins/Demigiant/DOTween/DOTween.XML.meta
  Assets/Plugins/Demigiant/DOTween/DOTween.dll
  Assets/Plugins/Demigiant/DOTween/DOTween.dll.meta
  Assets/Plugins/Demigiant/DOTween/Editor.meta
  Assets/Plugins/Demigiant/DOTween/Editor/DOTweenEditor.XML
  Assets/Plugins/Demigiant/DOTween/Editor/DOTweenEditor.XML.meta
  Assets/Plugins/Demigiant/DOTween/Editor/DOTweenEditor.dll
  Assets/Plugins/Demigiant/DOTween/Editor/DOTweenEditor.dll.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenIcon.png
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenIcon.png.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenMiniIcon.png
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenMiniIcon.png.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer.png
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer.png.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer_dark.png
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer_dark.png.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Header.jpg
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Header.jpg.meta
  Assets/Plugins/Demigiant/DOTween/Modules.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleAudio.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleAudio.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleEPOOutline.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleEPOOutline.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModulePhysics.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModulePhysics.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModulePhysics2D.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModulePhysics2D.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleSprite.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleSprite.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUI.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUI.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUnityVersion.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUnityVersion.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUtils.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUtils.cs.meta
  Assets/Plugins/Demigiant/DOTween/readme.txt
  Assets/Plugins/Demigiant/DOTween/readme.txt.meta
  Assets/Resources.meta
  Assets/Resources/DOTweenSettings.asset
  Assets/Resources/DOTweenSettings.asset.meta
Labels: priority: high, status: in progress

#71 69 qualia intensity implementation
  Assets/Scripts/QualiaIntensity.cs
  Assets/Scripts/QualiaIntensity.cs.meta
Labels: status: review needed, status: approved, priority: medium, type: feature
